#syntax=docker/dockerfile-upstream:1.4.0-rc1
version: '3.8'
services:
    app:
        image: 'ketchersvc:latest-${FLAVOR}'
        ports:
            - 9000:9000
        environment:
            - CONFIG_PORT=9000
            - CONFIG_KETCHER_URL=https://chemotion/ketcher/
            - CONFIG_MIN_WORKERS=1
            - CONFIG_MAX_WORKERS=4
